Repository BirthdayResearch/quantum, pull requests merged in 2022-12, with the labels that each got.

#43 chore(setup): update repo to use `codex` tooling and standards
  .github/CODEOWNERS
  .github/renovate.json
  .github/workflows/ci-e2e.yml
  .github/workflows/ci.yml
  .gitignore
  .idea/README.md
  .idea/codex.iml
  .idea/modules.xml
  .npmrc
  .nvmrc
  .pnpmfile.cjs
  .prettierignore
  .vscode/.gitignore
  .vscode/extensions.json
  .vscode/settings.json
  apps/api/.editorconfig
  apps/api/.eslintrc
  apps/api/.gitignore
  apps/api/.nvmrc
  apps/api/nest-cli.json
  apps/api/package.json
  apps/api/src/app.controller.spec.ts
  apps/api/src/app.controller.ts
  apps/api/src/app.module.ts
  apps/api/src/app.service.ts
  apps/api/src/main.ts
  apps/api/test/app.e2e-spec.ts
  apps/api/test/jest-e2e.json
  apps/api/tsconfig.build.json
  apps/api/tsconfig.json
  apps/server/package.json
  apps/server/src/AppController.ts
  apps/server/src/AppModule.ts
  apps/server/src/AppProbeIndicator.ts
  apps/server/src/AppService.ts
  apps/server/src/main.ts
  apps/server/tsconfig.build.json
  apps/server/tsconfig.json
  apps/web/package.json
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/Footer.tsx
  apps/web/src/components/Header.tsx
  apps/web/src/components/InputSelector.tsx
  apps/web/src/components/ThemeSwitch.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/layouts/Base.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/styles/globals.scss
  apps/web/tsconfig.json
  package-lock.json
  package.json
  packages/tsconfig/base.json
  packages/tsconfig/package.json
  packages/tsconfig/web.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: kind/chore

#37 feature(ui-ux): move network selection into a context
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/InputSelector.tsx
  apps/web/src/contexts/NetworkContext.tsx
  apps/web/src/contexts/NetworkEnvironmentContext.tsx
  apps/web/src/layouts/Base.tsx
  apps/web/src/types.ts
Labels: kind/feature

#69 chore(renovate): Add renovate group for @birthdayresearch/sticky
  .github/renovate.json
Labels: kind/chore

#65 feature(ui-ux): create proof of assets section
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/DailyLimit.tsx
  apps/web/src/components/Header.tsx
  apps/web/src/components/MobileBottomMenu.tsx
  apps/web/src/components/ProofOfAssetsCard.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/commons/BottomModal.tsx
  apps/web/src/components/commons/ProgressBar.tsx
  apps/web/src/components/commons/Tooltip.tsx
  apps/web/src/components/icons/BrLogo.tsx
  apps/web/src/contexts/NetworkContext.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/styles/globals.scss
  apps/web/src/types.ts
  apps/web/tailwind.config.js
Labels: kind/feature

#74 feature(standard): setup `@waveshq/standard` tools
  .github/renovate.json
  .npmrc
  .prettierignore
  apps/web/.eslintrc
  apps/web/package.json
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/Header.tsx
  apps/web/src/components/InputSelector.tsx
  apps/web/src/components/ProofOfAssetsCard.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/icons/ArrowDownIcon.tsx
  apps/web/src/components/icons/SwitchIcon.tsx
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
  apps/web/src/layouts/contexts/ThemeProvider.tsx
  apps/web/src/utils/textHelper.ts
  apps/web/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: kind/feature

#50 feature(ui-ux): added quick input component
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/Footer.tsx
  apps/web/src/components/Header.tsx
  apps/web/src/components/InputSelector.tsx
  apps/web/src/components/ThemeSwitch.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/components/commons/QuickInputCard.tsx
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/styles/globals.scss
  pnpm-lock.yaml
Labels: kind/feature

#51 feat(Hardhat): Scaffold initial Hardhat container
  .github/workflows/ci.yml
  .npmrc
  apps/server/package.json
  package.json
  packages/smartcontracts/.gitignore
  packages/smartcontracts/.npmignore
  packages/smartcontracts/.npmrc
  packages/smartcontracts/.solhintignore
  packages/smartcontracts/Dockerfile
  packages/smartcontracts/package.json
  packages/smartcontracts/src/containers/EvmContractManager.ts
  packages/smartcontracts/src/containers/HardhatNetwork.ts
  packages/smartcontracts/src/containers/HardhatNetworkContainer.ts
  packages/smartcontracts/src/containers/Utils.ts
  packages/smartcontracts/src/containers/index.ts
  packages/smartcontracts/src/contracts/TestContract.sol
  packages/smartcontracts/src/envvar.ts
  packages/smartcontracts/src/hardhat.config.ts
  packages/smartcontracts/src/index.ts
  packages/smartcontracts/src/tests/TestContract.spec.ts
  packages/smartcontracts/test-i9n/EvmContractManager.i9n.ts
  packages/smartcontracts/test-i9n/HardhatNetwork.i9n.ts
  packages/smartcontracts/tsconfig.build.json
  packages/smartcontracts/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: kind/feature

#73 feature(ui-ux): add info icon tooltip for web and mobile
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/DailyLimit.tsx
  apps/web/src/components/ProofOfAssetsCard.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/components/commons/BottomModal.tsx
  apps/web/src/components/commons/IconTooltip.tsx
Labels: kind/feature

#85 feature(ui-ux): add common cta button
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/styles/globals.scss
  apps/web/src/types.ts
Labels: kind/feature

#92 chore(setup): add `@waveshq/standard-defichain-jellyfishsdk` and fix …
  README.md
  apps/server/package.json
  apps/web/package.json
  netlify.toml
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: kind/chore

#97 feature(ui-ux): add local enviroment option on dev mode
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
  apps/web/src/types.ts
Labels: kind/feature

#115 fix(deps): redirect netlify issue
  .github/workflows/ci-e2e.yml
  .npmrc
  apps/web/package.json
  package.json
  pnpm-lock.yaml
Labels: kind/fix

#108 feature(ui-ux): add 404 not found page
  apps/web/src/pages/404.tsx
Labels: kind/feature

#99 feature(ui-ux): transfer confirmation modal
  apps/web/package.json
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/DailyLimit.tsx
  apps/web/src/components/MobileBottomMenu.tsx
  apps/web/src/components/ProofOfAssetsCard.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/components/commons/BottomModal.tsx
  apps/web/src/components/commons/IconTooltip.tsx
  apps/web/src/components/commons/ProgressStepIndicator.tsx
  apps/web/src/components/commons/ProgressStepIndicatorMobile.tsx
  apps/web/src/components/commons/Tooltip.tsx
  apps/web/src/components/commons/UtilityButton.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/StepOneSendConfirmation.tsx
  apps/web/src/components/erc-transfer/StepThreeClaim.tsx
  apps/web/src/components/erc-transfer/StepTwoVerification.tsx
  apps/web/src/components/erc-transfer/TimeLimitCounter.tsx
  apps/web/src/components/icons/BrLogoIcon.tsx
  apps/web/src/constants.ts
  apps/web/src/hooks/useCopyToClipboard.tsx
  apps/web/src/hooks/useDisableEscapeKey.ts
  apps/web/src/hooks/useResponsive.ts
  apps/web/src/types.ts
  apps/web/src/utils/durationHelper.tsx
  apps/web/tailwind.config.js
  pnpm-lock.yaml
Labels: kind/feature

#127 feature(ui-ux): add retry feature for unconfirmed transaction
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/components/commons/AlertInfoMessage.tsx
  apps/web/src/components/commons/QuickInputCard.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/StepOneSendConfirmation.tsx
  apps/web/src/components/erc-transfer/StepThreeClaim.tsx
  apps/web/src/components/erc-transfer/StepTwoVerification.tsx
  apps/web/src/constants.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
  apps/web/src/types.ts
  apps/web/src/utils/localStorage.tsx
Labels: kind/feature

#149 feature(setup): initial setup of DeFiChainModule
  .github/CODEOWNERS
  apps/server/docker-compose.yml
  apps/server/package.json
  apps/server/src/AppConfig.ts
  apps/server/src/AppModule.ts
  apps/server/src/BridgeServerApp.ts
  apps/server/src/defichain/DeFiChainModule.ts
  apps/server/src/defichain/controllers/StatsController.ts
  apps/server/src/defichain/model/NetworkDto.ts
  apps/server/src/defichain/providers/WhaleApiClientProvider.ts
  apps/server/src/defichain/services/WhaleApiService.ts
  apps/server/test-i9n/BridgeApp.i9n.ts
  packages/smartcontracts/package.json
  packages/smartcontracts/src/hardhat.config.ts
  packages/smartcontracts/src/index.ts
  packages/smartcontracts/src/tests/TestContract.spec.ts
  packages/smartcontracts/test-i9n/EvmContractManager.i9n.ts
  pnpm-lock.yaml
Labels: kind/feature
