Repository BirthdayResearch/quantum, pull requests merged in 2023-01, with the labels that each got.

#148 feat(SmartContracts): migrating smart contracts
  .github/workflows/ci.yml
  packages/smartcontracts/package.json
  packages/smartcontracts/src/contracts/BridgeProxy.sol
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/contracts/TestContract.sol
  packages/smartcontracts/src/contracts/TestToken.sol
  packages/smartcontracts/src/hardhat.config.ts
  packages/smartcontracts/src/tests/BridgeProxy.spec.ts
  packages/smartcontracts/test-i9n/Bridge.i9n.ts
  pnpm-lock.yaml
Labels: kind/feature

#181 chore(workflow): Add contract and server area label
  .github/labels.yml
Labels: kind/chore

#191 feature(ui-ux): connect metamask wallet on localhost
  apps/server/src/AppController.ts
  apps/server/src/AppService.ts
  apps/web/next.config.js
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/layouts/Base.tsx
Labels: kind/feature

#202 chore(deps): bump wagmi and connectkit
  .github/CODEOWNERS
  apps/web/package.json
  apps/web/src/layouts/Base.tsx
  pnpm-lock.yaml
Labels: kind/chore

#211 feature(api): setup api rate limiter to avoid spamming
  apps/server/package.json
  apps/server/src/AppModule.ts
  pnpm-lock.yaml
Labels: kind/feature

#212 feat(SmartContracts): Deployment script for Goerli test net
  README.md
  packages/smartcontracts/package.json
  packages/smartcontracts/src/.env.example
  packages/smartcontracts/src/hardhat.config.ts
  packages/smartcontracts/src/scripts/deployBridgeImplementation.ts
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/scripts/deployERC20.ts
  pnpm-lock.yaml
Labels: kind/feature

#224 chore(contracts): Add Hardhat task for better dApp integration devx
  packages/smartcontracts/README.md
  packages/smartcontracts/package.json
  packages/smartcontracts/src/hardhat.config.ts
  packages/smartcontracts/src/tests/SetupLocalTestTask.spec.ts
Labels: kind/chore

#227 feat(Contracts): cleaner helper functions and switch to calldata
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
  packages/smartcontracts/src/tests/testUtils/mathUtils.ts
Labels: kind/feature

#225 chore(Contracts): Added script for minting and approving test tokens on Goerli testnet
  README.md
  packages/smartcontracts/src/scripts/mintTestToken.ts
Labels: kind/chore

#188 docs(ReadMe): Documenting smart contracts and it's function
  README.md
  packages/smartcontracts/src/contracts/BridgeV1.sol
Labels: kind/docs

#223 feature(apps/server): initialize whale-wallet-* for ops on DeFiChain
  apps/server/docker-compose.yml
  apps/server/package.json
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/DeFiChainModule.ts
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/defichain/providers/WhaleWalletProvider.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/modules/EthersModule.ts
  apps/server/test-i9n/BridgeApp.i9n.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  apps/server/test-i9n/defichain/wallet.i9n.ts
  apps/web/docker-compose.yml
  apps/web/package.json
  package.json
  pnpm-lock.yaml
Labels: kind/feature

#235 fix(build): fix issue on web build
  apps/web/package.json
  apps/web/src/layouts/Base.tsx
  pnpm-lock.yaml
Labels: kind/fix

#244 chore(docker): use shared docker-compose for client and server
  .github/workflows/ci-e2e.yml
  apps/server/package.json
  apps/web/docker-compose.yml
  apps/web/package.json
  docker-compose.yml
Labels: kind/chore

#243 feat(Contracts): Pin OpenZeppelin version
  .github/renovate.json
  packages/smartcontracts/package.json
  pnpm-lock.yaml
Labels: kind/feature

#204 feature(api): setup postgresql for db connectivity
  apps/server/.env
  apps/server/package.json
  apps/server/prisma/client.ts
  apps/server/prisma/migrations/20230117060513_init/migration.sql
  apps/server/prisma/migrations/migration_lock.toml
  apps/server/prisma/schema.prisma
  apps/server/test-i9n/PostgreSql.i9n.ts
  docker-compose.yml
  pnpm-lock.yaml
Labels: kind/feature

#258 feat(core): display token balance instead of overall balance
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/types.ts
Labels: kind/feature

#242 feat(Contracts): Local and Mainnet deployment scripts
  README.md
  packages/smartcontracts/README.md
  packages/smartcontracts/src/.env.example
  packages/smartcontracts/src/hardhat.config.ts
  packages/smartcontracts/src/scripts/deployBridgeImplementation.ts
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/scripts/deployERC20.ts
  packages/smartcontracts/src/scripts/goerliMintApprove.ts
  packages/smartcontracts/src/scripts/localContractsDeployment.ts
  packages/smartcontracts/src/scripts/mainnetContractsDeployment.ts
  packages/smartcontracts/src/tests/LocalTest.spec.ts
  packages/smartcontracts/src/tests/SetupLocalTestTask.spec.ts
Labels: kind/feature

#232 feat(ui-ux): add initial smart contract integration for EVM to DFC transfer
  apps/web/cypress/e2e/bridge.spec.ts
  apps/web/cypress/e2e/index.spec.ts
  apps/web/next.config.js
  apps/web/package.json
  apps/web/src/api/logging.ts
  apps/web/src/api/secure-storage/index.ts
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/components/commons/Modal.tsx
  apps/web/src/components/commons/QuickInputCard.tsx
  apps/web/src/config/BridgeV1Abi.json
  apps/web/src/config/contractAddresses.ts
  apps/web/src/constants.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/ContractContext.tsx
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
  apps/web/src/types.ts
  apps/web/tailwind.config.js
  pnpm-lock.yaml
Labels: kind/feature
