Repository BirthdayResearch/quantum, pull requests merged in 2023-02, with the labels that each got.

#247 feature(ui-ux): transaction flow for DFC to ERC20
  apps/web/public/verified-16x16.svg
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/components/commons/IconTooltip.tsx
  apps/web/src/components/commons/ProgressStepIndicator.tsx
  apps/web/src/components/commons/UtilityButton.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/components/erc-transfer/StepOneInitiate.tsx
  apps/web/src/components/erc-transfer/StepThreeClaim.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/components/erc-transfer/StepTwoVerification.tsx
  apps/web/src/components/erc-transfer/TimeLimitCounter.tsx
  apps/web/src/components/erc-transfer/VerifiedUtilityButton.tsx
  apps/web/src/constants.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/styles/globals.scss
Labels: kind/feature

#268 fix(ui-ux): always use bridge proxy contract address to write
  README.md
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
Labels: kind/fix

#256 feat(EVMTransactionConfirmer): Build getAllEventsFromBlockNumber function and integration tests
  apps/server/src/AppConfig.ts
  apps/server/src/AppController.ts
  apps/server/src/AppService.ts
  apps/server/test-i9n/BridgeApp.i9n.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  apps/server/test-i9n/defichain/wallet.i9n.ts
Labels: kind/feature

#275 feature(ui-ux): error modal common component
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/components/commons/ErrorModal.tsx
Labels: kind/feature

#296 feature(server): network updates and playground container support
  apps/server/package.json
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/model/NetworkDto.ts
  apps/server/src/defichain/providers/WhaleApiClientProvider.ts
  apps/server/src/defichain/providers/WhaleWalletProvider.ts
  apps/server/src/defichain/services/WhaleApiService.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  apps/server/test-i9n/defichain/wallet.i9n.ts
  apps/web/package.json
  docker-compose.yml
  package.json
  packages/smartcontracts/package.json
  pnpm-lock.yaml
Labels: kind/feature

#267 docs(ReadMe): Updated readMe & indexed fields on events.
  README.md
  packages/smartcontracts/src/contracts/BridgeV1.sol
Labels: kind/docs

#311 chore(testing): Bridge contracts related test fixtures for DRY-ness
  .github/renovate.json
  apps/server/src/AppConfig.ts
  apps/server/src/AppService.ts
  apps/server/src/modules/EthersModule.ts
  apps/server/test-i9n/BridgeApp.i9n.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  apps/server/test-i9n/defichain/wallet.i9n.ts
  apps/server/test-i9n/testing/BridgeContractFixture.i9n.ts
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  apps/server/test-i9n/testing/BridgeServerTestingApp.ts
  apps/server/test-i9n/testing/TestingModule.ts
  docker-compose.yml
  package.json
  packages/smartcontracts/package.json
  packages/smartcontracts/src/tests/testUtils/mathUtils.ts
  turbo.json
Labels: kind/chore

#297 feature(server): DeFiChain Transaction service
  apps/server/package.json
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/DeFiChainModule.ts
  apps/server/src/defichain/providers/WhaleApiClientProvider.ts
  apps/server/src/defichain/services/DeFiChainTransactionService.ts
  apps/server/src/defichain/services/SendService.ts
  apps/server/test-i9n/defichain/DeFiChainStubContainer.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/server/test-i9n/defichain/send.i9n.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  pnpm-lock.yaml
  turbo.json
Labels: kind/feature

#317 chore(tests): update renovate logic and moved out timeouts
  .github/renovate.json
  apps/server/test-i9n/defichain/DeFiChainStubContainer.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/server/test-i9n/defichain/send.i9n.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  pnpm-lock.yaml
Labels: kind/chore

#290 feat(core): request spend limit approval from user via metamask
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/commons/ErrorModal.tsx
  apps/web/src/components/commons/NumericFormat.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/config/ABIs/mainnet/BridgeV1.json
  apps/web/src/config/ABIs/testnet/BridgeV1.json
  apps/web/src/config/contractAddresses.ts
  apps/web/src/config/index.ts
  apps/web/src/constants.ts
  apps/web/src/hooks/useTransferFee.ts
  apps/web/src/hooks/useWriteApproveToken.ts
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
  apps/web/src/layouts/contexts/ContractContext.tsx
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/types.ts
Labels: kind/feature

#331 feature(apps/server): DeFiChain - set network to config
  apps/server/.env
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/controllers/StatsController.ts
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/defichain/model/NetworkDto.ts
  apps/server/src/defichain/providers/WhaleApiClientProvider.ts
  apps/server/src/defichain/providers/WhaleWalletProvider.ts
  apps/server/src/defichain/services/DeFiChainTransactionService.ts
  apps/server/src/defichain/services/SendService.ts
  apps/server/src/defichain/services/WhaleApiService.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/server/test-i9n/defichain/send.i9n.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
Labels: kind/feature

#337 chore(config): Consolidate Ethereum configs
  apps/server/.env
  apps/server/src/AppConfig.ts
  apps/server/src/AppService.ts
  apps/server/src/modules/EthersModule.ts
  apps/server/test-i9n/testing/TestingModule.ts
Labels: kind/chore

#346 feat(Contracts): Added name and version constants to contract
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.deployment.spec.ts
  packages/smartcontracts/src/tests/testUtils/deployment.ts
  packages/smartcontracts/test-i9n/Bridge.i9n.ts
Labels: kind/feature

#323 chore(contracts): Add flushFunds function
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/scripts/localContractsDeployment.ts
  packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
  packages/smartcontracts/src/tests/LocalTest.spec.ts
  packages/smartcontracts/src/tests/testUtils/deployment.ts
  packages/smartcontracts/test-i9n/Bridge.i9n.ts
  pnpm-lock.yaml
Labels: kind/chore

#356 feat(SmartContracts): Implement community address
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/scripts/localContractsDeployment.ts
  packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.deployment.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
  packages/smartcontracts/src/tests/testUtils/deployment.ts
  packages/smartcontracts/test-i9n/Bridge.i9n.ts
Labels: kind/feature

#364 fix(code improvements): clean up code
  apps/server/test-i9n/BridgeApp.i9n.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/server/test-i9n/defichain/send.i9n.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
Labels: kind/fix

#369 chore(devx): Add README on how to run the server locally
  apps/server/README.md
  apps/server/package.json
Labels: kind/chore

#363 chore(docker): build server app
  .github/scripts/release-ecr-tags.js
  .github/scripts/release-report.js
  .github/scripts/release-tags.js
  .github/workflows/ci-e2e.yml
  .github/workflows/ci.yml
  .github/workflows/ci/wait-for
  .github/workflows/release-apps.yml
  apps/nest-cli.json
  apps/server/Dockerfile
Labels: kind/chore

#349 feat(ui-ux): claim funds from ui
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/commons/ErrorModal.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/utils/durationHelper.tsx
Labels: kind/feature

#344 feat(server): sign claims data (reopen)
  apps/server/src/AppConfig.ts
  apps/server/src/AppService.ts
  apps/server/src/utils/MathUtils.ts
Labels: kind/feature

#378 fix(.idea): fix bridge.iml linking
  .idea/bridge.iml
  .idea/codex.iml
  .idea/modules.xml
Labels: kind/fix

#376 chore(server): Refactor for EthereumTransactionConfirmerService
  apps/server/src/AppController.ts
  apps/server/src/AppModule.ts
  apps/server/src/ethereum/EthereumModule.ts
  apps/server/src/ethereum/controllers/EthereumController.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/src/pipes/EthereumTransactionValidation.pipe.ts
  apps/server/test-i9n/ethereum/transactionConfirmer.i9n.ts
Labels: kind/chore

#342 feature(ui-ux): added refund address logic
  apps/server/prisma/migrations/20230208100243_init/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/web/package.json
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/commons/AddressError.tsx
  apps/web/src/components/commons/CircularProgress.tsx
  apps/web/src/components/commons/UtilityButton.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/StepOneInitiate.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/components/erc-transfer/TimeLimitCounter.tsx
  apps/web/src/constants.ts
  apps/web/src/hooks/useBridgeFormStorageKeys.ts
  apps/web/src/hooks/useTimeCounter.ts
  apps/web/src/store/website.tsx
  apps/web/src/styles/globals.scss
  apps/web/src/types.ts
  apps/web/src/utils/durationHelper.tsx
  pnpm-lock.yaml
Labels: kind/feature

#387 feat(EVMTransactionConfirmer): Return number of confirmations for UI
  apps/server/src/ethereum/controllers/EthereumController.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/ethereum/transactionConfirmer.i9n.ts
Labels: kind/feature

#371 feat(server): add health check service for database
  apps/server/package.json
  apps/server/src/AppModule.ts
  apps/server/src/HealthController.ts
  apps/server/src/health/PrismaHealth.ts
  apps/server/src/modules/HealthModule.ts
  apps/server/test-i9n/testing/HealthService.i9n.ts
  pnpm-lock.yaml
Labels: kind/feature

#372 chore(contracts): Implement TestBridge for QA testing
  packages/smartcontracts/src/contracts/TestBridge.sol
  packages/smartcontracts/src/scripts/localContractsDeployment.ts
  packages/smartcontracts/src/tests/LocalTest.spec.ts
  packages/smartcontracts/src/tests/TestBridgeProxy.defiToEvm.spec.ts
Labels: kind/chore

#392 feature(ui-ux): add banner
  apps/web/src/components/Banner.tsx
  apps/web/src/components/Header.tsx
Labels: kind/feature

#348 feat(ui-ux): evm token - set recommended spending limit to maxint
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/constants.ts
  apps/web/src/hooks/useWriteApproveToken.ts
Labels: kind/feature

#396 chore(workflow): add a workflow to deploy to staging on main
  .github/workflows/ci-db-staging.yml
  .github/workflows/ci.yml
  package.json
  turbo.json
Labels: kind/chore

#379 chore(workflows): add AWS login for ECR via OIDC
  .github/scripts/release-ecr-tags.js
  .github/scripts/release-report.js
  .github/workflows/release-apps.yml
  apps/nest-cli.json
Labels: kind/chore

#403 chore(server): updted logic for container mnemonic to use from env variable
  apps/server/.env
  apps/server/test-i9n/defichain/containers/DeFiChainStubContainer.ts
Labels: kind/chore

#330 feat(core): verify funds - DFC -> EVM
  apps/server/src/CustomErrorCodes.ts
  apps/server/src/HealthController.ts
  apps/server/src/ThrottleLimitConfig.ts
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/defichain/model/VerifyDto.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/web/package.json
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/store/website.tsx
  apps/web/src/types.ts
Labels: kind/feature

#411 feat(ui/ux): update metatags
  apps/web/public/bridge_share.png
  apps/web/public/favicon-16x16.png
  apps/web/public/favicon-32x32.png
  apps/web/public/favicon-64x64.png
  apps/web/public/favicon.ico
  apps/web/src/components/siteInfo.ts
  apps/web/src/layouts/Base.tsx
Labels: kind/feature

#417 feature(ui-ux): Transaction status progress bar
  apps/web/src/components/TransactionConfirmationProgressBar.tsx
  apps/web/src/components/TransactionStatus.tsx
Labels: kind/feature

#393 feature(api): added cache implementation for api call
  apps/server/package.json
  apps/server/src/AppModule.ts
  apps/server/src/defichain/DeFiChainModule.ts
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/libs/caches/GlobalCache.ts
  apps/server/src/libs/caches/SemaphoreCache.ts
  apps/server/test-i9n/testing/SemaphoreCache.i9n.ts
  pnpm-lock.yaml
Labels: kind/feature

#406 feat(Contracts): Removing allowance/daily limit
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/contracts/TestBridge.sol
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/scripts/localContractsDeployment.ts
  packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
  packages/smartcontracts/src/tests/LocalTest.spec.ts
  packages/smartcontracts/src/tests/TestBridgeProxy.defiToEvm.spec.ts
  packages/smartcontracts/src/tests/testUtils/deployment.ts
  packages/smartcontracts/test-i9n/Bridge.i9n.ts
Labels: kind/feature

#414 feature(ui-ux): transaction status (wip)
  apps/web/src/components/TransactionConfirmationProgressBar.tsx
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/pages/index.tsx
Labels: kind/feature

#422 chore(ui-ux): close transaction button for tablet and mobile
  apps/web/src/components/TransactionStatus.tsx
Labels: kind/chore

#412 chore(ui-ux): Consortium & Daily limit cleanup
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/DailyLimit.tsx
  apps/web/src/components/MobileBottomMenu.tsx
  apps/web/src/components/ProofOfAssetsCard.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/constants.ts
  apps/web/src/pages/index.tsx
Labels: kind/chore

#436 feature(core): transaction fees adjustment
  apps/web/src/hooks/useTransferFee.ts
Labels: kind/feature

#432 chore(ui-ux): skeleton loader for pending transaction status
  apps/web/package.json
  apps/web/src/components/TransactionConfirmationProgressBar.tsx
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/hooks/useWatchEthTxn.ts
  apps/web/src/pages/index.tsx
  pnpm-lock.yaml
Labels: kind/chore

#427 chore(smartcontracts): Add support for ETH to smart contracts
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
Labels: kind/chore

#434 feat(core): Add dynamic server URL
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/config/networkUrl.ts
  apps/web/src/hooks/useWrappedLazyQuery.ts
  apps/web/src/hooks/useWrappedMutation.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/store/defichain.tsx
Labels: kind/feature

#438 fix(ui-ux): styling header and footer for smaller width
  apps/web/src/components/Footer.tsx
  apps/web/src/components/Header.tsx
Labels: kind/fix

#440 fix(core): multiple poll on consecutive transaction triggered
  apps/web/src/hooks/useWatchEthTxn.ts
  apps/web/src/pages/index.tsx
Labels: kind/fix

#425 chore(workflow): fix release reporting
  .github/workflows/release-apps.yml
Labels: kind/chore

#430 feature(ui-ux): status api integration
  .github/renovate.json
  .github/scripts/release-ecr-tags.js
  .github/scripts/release-report.js
  .github/scripts/release-tags.js
  .github/workflows/ci-db-staging.yml
  .github/workflows/ci.yml
  .github/workflows/release-apps.yml
  README.md
  apps/web/cypress/e2e/maintenance.spec.ts
  apps/web/next.config.js
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/Maintenance.tsx
  apps/web/src/components/ScreenContainer.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/layouts/Base.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/store/index.ts
  apps/web/src/store/status.ts
  apps/web/src/types.ts
  turbo.json
Labels: kind/feature

#444 fix(ui-ux): assume bridge is up unless explicitly returned by api
  apps/web/src/components/ScreenContainer.tsx
Labels: kind/fix

#408 feat(core): trigger signClaim when verification is successful
  apps/server/.env
  apps/server/package.json
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/DeFiChainModule.ts
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/defichain/model/VerifyDto.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/EthereumModule.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/src/utils/DateUtils.ts
  apps/server/src/utils/MathUtils.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  apps/web/package.json
  apps/web/src/components/Banner.tsx
  apps/web/src/components/Footer.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/types.ts
  apps/web/src/utils/durationHelper.tsx
  pnpm-lock.yaml
Labels: kind/feature

#429 feat(ui-ux): update bridge proxy contract address
  apps/server/.env
  apps/web/src/config/ABIs/mainnet/BridgeV1.json
  apps/web/src/config/ABIs/testnet/BridgeV1.json
  apps/web/src/config/index.ts
Labels: kind/feature

#407 feat(core): evm to dfc flow
  apps/web/package.json
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/DailyLimit.tsx
  apps/web/src/components/MobileBottomMenu.tsx
  apps/web/src/components/ProofOfAssetsCard.tsx
  apps/web/src/components/TransactionConfirmationProgressBar.tsx
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/constants.ts
  apps/web/src/hooks/useBridgeFormStorageKeys.ts
  apps/web/src/hooks/useWatchEthTxn.ts
  apps/web/src/hooks/useWriteApproveToken.ts
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/TransactionHashContext.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/store/index.ts
  apps/web/src/utils/localStorage.tsx
  pnpm-lock.yaml
Labels: kind/feature

#420 feat(server): signclaim - set deadline to 24hours after creation
  apps/server/src/utils/DateUtils.ts
Labels: kind/feature

#439 feat(ui-ux): bring back support for ETH and remove wETH
  apps/web/src/config/ABIs/mainnet/BridgeV1.json
  apps/web/src/config/ABIs/testnet/BridgeV1.json
  apps/web/src/config/index.ts
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/types.ts
Labels: kind/feature

#449 feat(core): add Version api
  apps/server/.env
  apps/server/src/AppModule.ts
  apps/server/src/version/VersionController.ts
  apps/server/src/version/VersionInterface.ts
  apps/server/src/version/VersionModule.ts
  apps/server/test-i9n/testing/VersionService.i9n.ts
Labels: kind/feature

#448 feat(ui-ux): temporarily hide MainNet network
  apps/web/cypress/e2e/bridge.spec.ts
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
Labels: kind/feature

#450 fix(core): verify api not working as intended
  apps/web/src/components/ScreenContainer.tsx
  apps/web/src/config/networkUrl.ts
  apps/web/src/hooks/useWrappedLazyQuery.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/store/index.ts
  apps/web/src/store/status.ts
Labels: kind/fix

#451 feat(core): send fund after 65 confirmations
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/constants.ts
  apps/web/src/hooks/useBridgeFormStorageKeys.ts
  apps/web/src/hooks/useWatchEthTxn.ts
  apps/web/src/layouts/contexts/TransactionHashContext.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/store/index.ts
Labels: kind/feature

#447 fix(ui-ux): styling
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/commons/ProgressStepIndicator.tsx
  apps/web/src/components/erc-transfer/StepOneInitiate.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
Labels: kind/fix

#457 chore(workflow): expose port on images build
  apps/server/Dockerfile
Labels: kind/chore

#452 fix(ui-ux): fix race condition when calling SC's write function
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
Labels: kind/fix

#459 feature(ui-ux): fix verify function not catching error
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
Labels: kind/feature

#468 fix(ui-ux): fix incorrectly displayed insufficient allowance
  apps/web/src/components/BridgeForm.tsx
Labels: kind/fix

#469 chore(test): check that deadline is only set to 24hr
  apps/server/test-i9n/defichain/verify.i9n.ts
Labels: kind/chore

#472 chore(ops): setup temporary domain for remote playground
  apps/web/next.config.js
  apps/web/src/config/networkUrl.ts
Labels: kind/chore

#477 feat(server): update bridge proxy to v2
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
Labels: kind/feature

#460 chore(e2e): added integration test for allocate fund
  apps/server/prisma/migrations/20230221053615_v0_1_1/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/server/test-i9n/ethereum/allocateDFCFund.i9n.ts
  apps/server/test-i9n/helper/sleep.ts
Labels: kind/chore

#466 chore(server): log some info for core functions
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
Labels: kind/chore

#478 feat(DFC Balance): added service and integration tests to get asset balance of hotwallet
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/controllers/EthereumController.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/defichain/balance.i9n.ts
Labels: kind/feature

#400 feature(ui-ux): display browser reload modal
  apps/web/src/pages/index.tsx
Labels: kind/feature

#480 chore(server): handleTransaction - increase throttle limit
  apps/server/src/ethereum/controllers/EthereumController.ts
Labels: kind/chore

#483 feat(ui-ux): add transition to connect wallet button
  apps/web/src/components/ConnectButton.tsx
Labels: kind/feature

#484 chore(server): log send details
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
Labels: kind/chore

#486 fix(ui-ux): disable verify transfer when no address is generated
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
Labels: kind/fix

#482 fix(server): fixed eth transfer flow for allocate fund
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/src/utils/TokensUtils.ts
  apps/server/test-i9n/ethereum/allocateDFCFund.i9n.ts
  apps/server/test-i9n/testing/BridgeContractFixture.ts
Labels: kind/fix

#481 feature(ui-ux): add documentation, faq url and add timeout function on DFC > EVM verify function
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/MobileBottomMenu.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/hooks/useSetTimeout.ts
  apps/web/src/pages/index.tsx
Labels: kind/feature

#492 fix(evm balance): reworked service to returned appropriate asset dp
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/ethereum/transactionConfirmer.i9n.ts
Labels: kind/fix

#491 chore(ui-ux): handle failed txn
  apps/web/src/components/TransactionConfirmationProgressBar.tsx
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/layouts/contexts/TransactionHashContext.tsx
  apps/web/src/pages/index.tsx
Labels: kind/chore

#501 fix(web): added amount validation for small number
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
Labels: kind/fix

#512 fix(ui-ux): hide top faq and documentation in mobile
  apps/web/src/components/WelcomeHeader.tsx
Labels: kind/fix

#507 feat(core): deduct fee on evm to dfc
  apps/server/.env
  apps/server/src/AppConfig.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/ethereum/allocateDFCFund.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  package.json
Labels: kind/feature

#424 docs(ReadMe): Updated readme. Minor changes on smart contract and deployment script
  README.md
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol
  packages/smartcontracts/src/hardhat.config.ts
  packages/smartcontracts/src/scripts/goerliMintApprove.ts
  packages/smartcontracts/src/scripts/mainnetContractsDeployment.ts
  packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
Labels: kind/docs

#503 feat(server): signclaim - store claim details on db to prevent possible multiple claims
  apps/server/prisma/migrations/20230222202410_v0_1_2/migration.sql
  apps/server/prisma/migrations/migration_lock.toml
  apps/server/prisma/schema.prisma
  apps/server/src/defichain/controllers/WhaleWalletController.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/ethereum/signClaims.i9n.ts
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/feature

#516 fix(ui-ux): hover state
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/InputSelector.tsx
Labels: kind/fix

#515 fix(server): prevent negative number of confirmations on
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
Labels: kind/fix

#500 feat(core): deduct fee from DFC > EVM transaction
  apps/server/.env
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/feature

#521 feature(server): added ability to update mnemonic to manage diff DeFiChainAddressIndex version
  apps/server/prisma/migrations/20230223061929_v0_1_3/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/defichain/address.i9n.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/ethereum/signClaims.i9n.ts
Labels: kind/feature

#524 feat(server): store eth receiver address to DB
  apps/server/prisma/migrations/20230223083837_v0_1_4/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
Labels: kind/feature

#526 feat(core): add /balances api to get wallet balance
  apps/server/src/AppModule.ts
  apps/server/src/balances/BalancesController.ts
  apps/server/src/balances/BalancesInterface.ts
  apps/server/src/balances/BalancesModule.ts
  apps/server/src/balances/BalancesService.ts
  apps/server/src/defichain/DeFiChainModule.ts
  apps/server/test-i9n/balances/balances.i9n.ts
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  apps/server/test-i9n/testing/TestingModule.ts
Labels: kind/feature

#467 feat(smartcontracts): Fix bug in claimFund and add several security improvements
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol
  packages/smartcontracts/src/tests/BridgeImplementation.disableInitializer.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.deployment.spec.ts
  packages/smartcontracts/src/tests/testUtils/deployment.ts
Labels: kind/feature

#489 feat(ui-ux): remove playground env for Testnet testing
  apps/web/cypress/e2e/bridge.spec.ts
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/config/networkUrl.ts
Labels: kind/feature

#538 feature(server/defichain): fund UTXO on successful transactions
  .github/workflows/ci.yml
  apps/server/.env
  apps/server/jest.config.js
  apps/server/jest.sequencer.js
  apps/server/package.json
  apps/server/prisma/migrations/20230223144636_/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  packages/smartcontracts/package.json
  pnpm-lock.yaml
Labels: kind/feature

#540 chore(web): update abi to v4
  apps/web/src/config/ABIs/mainnet/BridgeV1.json
  apps/web/src/config/ABIs/testnet/BridgeV1.json
Labels: kind/chore

#541 fix(ui-ux): input amount overflow screen and switch source tooltip hover
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/pages/index.tsx
Labels: kind/fix

#539 fix(core): handle address details global state
  .github/workflows/ci.yml
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/components/erc-transfer/StepOneInitiate.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/constants.ts
  apps/web/src/hooks/useBridgeFormStorageKeys.ts
  apps/web/src/hooks/useWatchEthTxn.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/StorageContext.tsx
  apps/web/src/layouts/contexts/TransactionHashContext.tsx
  apps/web/src/pages/index.tsx
Labels: kind/fix

#498 feature(server): restrict cors on prod to allow only quantumbridge.app
  apps/server/src/BridgeServerApp.ts
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
Labels: kind/feature

#530 chore(ui-ux): updated placeholder text to Eth Address
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/types.ts
Labels: kind/chore

#547 chore(ui-ux): improve ui on read only refund address
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/StepOneInitiate.tsx
Labels: kind/chore

#548 chore(ui-ux): fixed modal flicker issue
  .github/workflows/ci.yml
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/erc-transfer/StepOneInitiate.tsx
Labels: kind/chore

#551 feature(ui-ux): Add confirmation modal upon resetting form
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/commons/UtilityModal.tsx
Labels: kind/feature

#550 chore(core): display local playground options when running in local
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/config/networkUrl.ts
Labels: kind/chore

#552 feat(ui-ux): handle error when contract has insufficient balance
  apps/web/src/components/commons/ErrorModal.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/feature

#553 chore(ui-ux): display wallet address warning on using local playground
  apps/web/src/components/WalletAddressInput.tsx
Labels: kind/chore

#556 fix(ui-ux): incorrect transfer fee
  apps/web/src/hooks/useTransferFee.ts
Labels: kind/fix

#475 feat(server): GA setup tags
  apps/web/next.config.js
  apps/web/src/layouts/Base.tsx
  apps/web/src/pages/_app.tsx
Labels: kind/feature

#554 feature(ui-ux): show txn hash for defiscan to track the EVM to DFC transfer
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/constants.ts
  apps/web/src/hooks/useBridgeFormStorageKeys.ts
  apps/web/src/hooks/useWatchEthTxn.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/DeFiScanContext.tsx
  apps/web/src/layouts/contexts/StorageContext.tsx
  apps/web/src/pages/index.tsx
Labels: kind/feature

#557 fix(ui-ux): fixed txn bug
  apps/web/src/layouts/contexts/StorageContext.tsx
Labels: kind/fix

#549 feat(ui-ux): show version number at homepage
  apps/web/src/components/Footer.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/store/index.ts
  apps/web/src/types.ts
Labels: kind/feature

#559 feat(ui-ux): display different message when claim is in progress
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/feature

#560 chore(server): added cache for /version api
  apps/server/src/libs/caches/GlobalCache.ts
  apps/server/src/version/VersionController.ts
  apps/server/src/version/VersionModule.ts
Labels: kind/chore

#566 fix(core): frontend - update hot wallets balance checker
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/hooks/useCheckBalance.ts
  apps/web/src/hooks/useTransferFee.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/types.ts
Labels: kind/fix

#569 fix(core): web - fix approval loop issue
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
Labels: kind/fix

#571 fix(core): web - fix sudden odd display of approval loader
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
Labels: kind/fix

#570 chore(ui-ux): bump connectkit version to 1.2.0
  apps/web/package.json
  pnpm-lock.yaml
Labels: kind/chore

#576 chore(ops): add another status for community wallet
  apps/server/prisma/migrations/20230227071459_/migration.sql
  apps/server/prisma/schema.prisma
Labels: kind/chore

#578 fix(core): use toFixed to prevent formatting to scientific notation
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/store/defichain.tsx
Labels: kind/fix

#586 fix(ui-ux): eth does not require approval
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
Labels: kind/fix

#590 chore(core): skip throttle
  apps/server/src/balances/BalancesController.ts
  apps/server/src/defichain/controllers/StatsController.ts
  apps/server/src/defichain/controllers/WhaleWalletController.ts
Labels: kind/chore

#573 chore(server): squashed migrations
  apps/server/prisma/migrations/000000000000_init/migration.sql
  apps/server/prisma/migrations/20230220053119_v0_1_0/migration.sql
  apps/server/prisma/migrations/20230221053615_v0_1_1/migration.sql
  apps/server/prisma/migrations/20230222202410_v0_1_2/migration.sql
  apps/server/prisma/migrations/20230223061929_v0_1_3/migration.sql
  apps/server/prisma/migrations/20230223083837_v0_1_4/migration.sql
  apps/server/prisma/migrations/20230223144636_/migration.sql
  apps/server/prisma/migrations/20230227071459_/migration.sql
  apps/server/prisma/migrations/20230227073814_/migration.sql
Labels: kind/chore

#561 refactor(ui-ux): add qr address to step 3 of dfc > evm
  apps/web/src/components/QrAddress.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/components/erc-transfer/TimeLimitCounter.tsx
Labels: kind/refactor

#558 feature(ui-ux): add utility modal to prevent accidental closing transaction modal
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/commons/ErrorModal.tsx
  apps/web/src/components/commons/UtilityModal.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/feature

#592 fix(ui-ux): quick input buttons
  apps/web/src/components/commons/QuickInputCard.tsx
Labels: kind/fix

#580 feat(Contract): Post Audit features request
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
Labels: kind/feature
