Repository BirthdayResearch/quantum, pull requests merged in 2023-03, with the labels that each got.

#597 chore(web): update abi
  apps/web/src/config/ABIs/mainnet/BridgeV1.json
  apps/web/src/config/ABIs/testnet/BridgeV1.json
Labels: kind/chore

#596 chore(api): updated server endpoints for testnet and mainnet
  apps/web/src/config/networkUrl.ts
Labels: kind/chore

#593 feature(ui-ux): restore flow for Erc > Dfc
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/erc-transfer/RestoreTransactionModal.tsx
  apps/web/src/hooks/useWatchEthTxn.ts
Labels: kind/feature

#574 fix(ui-ux): ui resizing for core component in initial state
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/components/Footer.tsx
  apps/web/src/components/Header.tsx
  apps/web/src/components/InputSelector.tsx
  apps/web/src/components/MobileBottomMenu.tsx
  apps/web/src/components/ScreenContainer.tsx
  apps/web/src/components/TransactionStatus.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/components/commons/QuickInputCard.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/pages/index.tsx
Labels: kind/fix

#599 chore(ui-ux): improve ux on step 2 (dfc -> evm)
  apps/web/src/components/commons/AlertInfoMessage.tsx
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/styles/globals.scss
Labels: kind/chore

#607 fix(ui-ux): revert bg-card-section opacity
  apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
  apps/web/src/styles/globals.scss
Labels: kind/fix

#591 fix(ui-ux): Minor ui bug fixes
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/WelcomeHeader.tsx
  apps/web/src/components/commons/QuickInputCard.tsx
Labels: kind/fix

#587 feat(smart contracts): Add timelock as per audit suggestions
  packages/smartcontracts/package.json
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/contracts/TimelockController.sol
  packages/smartcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/scripts/deployTimelockController.ts
  packages/smartcontracts/src/scripts/localContractsDeployment.ts
  packages/smartcontracts/src/scripts/mainnetContractsDeployment.ts
  packages/smartcontracts/src/tests/BridgeImplementation.disableInitializer.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.deployment.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.relayerAddress.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
  packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
  packages/smartcontracts/src/tests/LocalTest.spec.ts
  packages/smartcontracts/src/tests/TestContract.spec.ts
  packages/smartcontracts/src/tests/TimelockController.spec.ts
  packages/smartcontracts/src/tests/testUtils/deployment.ts
  packages/smartcontracts/test-i9n/Bridge.i9n.ts
  pnpm-lock.yaml
Labels: kind/feature

#609 fix(ui-ux): fix rounding up issue with 6dp
  apps/web/src/components/commons/QuickInputCard.tsx
  apps/web/src/hooks/useWatchEthTxn.ts
Labels: kind/fix

#611 chore(ui-ux): updated txn status and updated test case
  apps/server/test-i9n/defichain/balance.i9n.ts
  apps/server/test-i9n/ethereum/signClaims.i9n.ts
  apps/web/src/components/TransactionStatus.tsx
Labels: kind/chore

#619 chore(web): update client ABI to latest v5 version
  apps/web/src/config/ABIs/mainnet/BridgeV1.json
  apps/web/src/config/ABIs/testnet/BridgeV1.json
Labels: kind/chore

#618 chore(server): improve logged error details
  apps/server/src/BridgeServerApp.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
Labels: kind/chore

#610 fix(uix-ux): fix the rounding on number input
  apps/web/src/components/commons/QuickInputCard.tsx
Labels: kind/fix

#625 fix(ui-ux): fixed flicker issue for maintenance page
  apps/web/cypress/e2e/bridge.spec.ts
  apps/web/cypress/e2e/index.spec.ts
  apps/web/cypress/e2e/maintenance.spec.ts
  apps/web/src/components/Maintenance.tsx
  apps/web/src/components/ScreenContainer.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/types.ts
Labels: kind/fix

#630 chore(web): update network url for staging and prod
  apps/web/next.config.js
  apps/web/src/config/networkUrl.ts
Labels: kind/chore

#632 fix(core): update evm > dfc fee
  apps/server/.env
  apps/server/test-i9n/ethereum/allocateDFCFund.i9n.ts
  apps/web/src/hooks/useTransferFee.ts
Labels: kind/fix

#634 fix(server): prevent creation of defichain private keys if it's not 2…
  apps/server/package.json
  apps/server/src/defichain/providers/WhaleWalletProvider.ts
  apps/server/test-i9n/ethereum/signClaims.i9n.ts
  apps/server/test-i9n/ethereum/transactionConfirmer.i9n.ts
  apps/server/test-i9n/testing/HealthService.i9n.ts
  apps/server/test-i9n/testing/VersionService.i9n.ts
Labels: kind/fix

#629 feat(ui-ux): restore - validate that tx hash is from 'bridgeToDeFiChain'
  apps/web/src/components/erc-transfer/RestoreTransactionModal.tsx
Labels: kind/feature

#633 feat(Smart contracts): Fix solidity version + more tests
  README.md
  packages/smartcontracts/package.json
  packages/smartcontracts/src/contracts/BridgeProxy.sol
  packages/smartcontracts/src/contracts/BridgeV1.sol
  packages/smartcontracts/src/contracts/TimelockController.sol
  packages/smartcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol
  packages/smartcontracts/src/tests/TimelockController.spec.ts
  pnpm-lock.yaml
Labels: kind/feature

#631 fix(ui-ux): adjust fees and to receive on UI
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
Labels: kind/fix

#637 feat(server): add `/settings` api for settings shared with frontend
  apps/server/.env
  apps/server/src/AppConfig.ts
  apps/server/src/AppModule.ts
  apps/server/src/settings/SettingsController.ts
  apps/server/src/settings/SettingsInterface.ts
  apps/server/src/settings/SettingsModule.ts
  apps/web/src/hooks/useTransferFee.ts
  apps/web/src/store/defichain.tsx
  apps/web/src/store/index.ts
  apps/web/src/types.ts
Labels: kind/feature

#640 feat(Contracts): Added script to verify contracts after the deployment
  packages/smartcontracts/src/contracts/test/TestToken.sol
  packages/smartcontracts/src/scripts/deployBridgeImplementation.ts
  packages/smartcontracts/src/scripts/deployBridgeProxy.ts
  packages/smartcontracts/src/scripts/deployTimelockController.ts
  packages/smartcontracts/src/scripts/mainnetContractsDeployment.ts
  packages/smartcontracts/src/scripts/utils/verify.ts
Labels: kind/feature

#645 fix(core): fix incorrect claim amount
  apps/web/src/components/ConfirmTransferModal.tsx
Labels: kind/fix

#641 fix(api): verify amount with max 6 decimal
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
Labels: kind/fix

#642 fix(ui-ux): hide balance error if there is pending txn
  apps/web/src/components/BridgeForm.tsx
Labels: kind/fix

#643 fix(web): fix claim loop when deadline has lapsed
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/components/erc-transfer/TimeLimitCounter.tsx
  apps/web/src/hooks/useTimeCounter.ts
  apps/web/src/utils/durationHelper.tsx
Labels: kind/fix

#653 fix(ui-ux): fix stucked success copy message
  apps/web/src/components/QrAddress.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
Labels: kind/fix

#648 fix(ui-ux): fixed getBalance bug in retry claim
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/hooks/useCheckBalance.ts
  apps/web/src/utils/debounce.ts
Labels: kind/fix

#652 fix(ui-ux): avoid approving eth
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/hooks/useWriteApproveToken.ts
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
Labels: kind/fix

#655 chore(server): save claimable amount and token symbol to db
  apps/server/prisma/migrations/20230306055552_v0_1_0/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/defichain/model/VerifyDto.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/ethereum/signClaims.i9n.ts
Labels: kind/chore

#656 chore(api): check supported tokens in verify api
  apps/server/src/CustomErrorCodes.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
Labels: kind/chore

#657 chore(server): return network to `/settings` api and add tests
  apps/server/src/settings/SettingsController.ts
  apps/server/src/settings/SettingsInterface.ts
  apps/server/test-i9n/testing/SettingsController.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  apps/web/src/types.ts
Labels: kind/chore

#654 fix(ui-ux): aligned X and Close buttons in Transaction error modal
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/commons/ActionButton.tsx
  apps/web/src/components/commons/ErrorModal.tsx
  apps/web/src/components/commons/UtilityModal.tsx
  apps/web/src/components/erc-transfer/RestoreTransactionModal.tsx
Labels: kind/fix

#650 chore(mainnet): prepare mainnet display [Merge when ready to go on MainNet]
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConnectButton.tsx
  apps/web/src/components/EnvironmentNetworkSwitch.tsx
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/config/ABIs/mainnet/BridgeV1.json
  apps/web/src/config/index.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
Labels: kind/chore

#658 chore(ui-ux): add mainnet.infura domain to CSP
  apps/web/next.config.js
Labels: kind/chore

#660 chore(ui-ux): change to american english
  apps/web/src/components/WelcomeHeader.tsx
Labels: kind/chore

#659 chore(core): use infura url for mainnet
  apps/web/src/layouts/Base.tsx
Labels: kind/chore

#667 chore(ops): update pnpm
  .github/renovate.json
  .github/workflows/ci-db-staging.yml
  .github/workflows/ci.yml
  .npmrc
  apps/server/Dockerfile
  apps/server/package.json
  package.json
  pnpm-lock.yaml
Labels: kind/chore

#671 fix(ui-ux): prevent user from bridging when token is unsupported
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
  apps/web/src/hooks/useCheckBalance.ts
Labels: kind/fix

#674 chore(ops): update missing npm config to generate sitemaps
  .npmrc
  apps/web/src/components/siteInfo.ts
Labels: kind/chore

#681 fix(ui-ux): footer position and screen height
  apps/web/src/components/ScreenContainer.tsx
Labels: kind/fix

#622 docs(ReadMe): Updated with correct addresses and user guide on new implementation
  README.md
  packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
  packages/smartcontracts/src/tests/testUtils/deployment.ts
Labels: kind/docs

#682 fix(api): update error codes
  apps/server/src/CustomErrorCodes.ts
Labels: kind/fix

#684 fix(core): claim - properly parse amount based on the token
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/fix

#686 chore(readme): Update README.md
  README.md
Labels: kind/chore

#687 fix(server): update wbtc mapping
  apps/server/src/utils/TokensUtils.ts
  apps/web/src/config/index.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/types.ts
Labels: kind/fix

#690 chore(refactor): lighthouse improvements
  apps/web/next.config.js
  apps/web/public/background/desktop.png
  apps/web/public/background/desktop.webp
  apps/web/public/background/mobile.png
  apps/web/public/background/mobile.webp
  apps/web/public/background/tablet.png
  apps/web/public/background/tablet.webp
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ScreenContainer.tsx
  apps/web/src/components/commons/Socials.tsx
  apps/web/src/components/commons/Tooltip.tsx
Labels: kind/chore

#699 fix(ui-ux): change to 5dp
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/commons/QuickInputCard.tsx
  apps/web/src/components/erc-transfer/StepThreeVerification.tsx
Labels: kind/fix

#701 fix(core): fix allowance error on mainnet
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
Labels: kind/fix

#705 feature(web): add raygun and compression
  apps/server/package.json
  apps/server/src/BridgeServerApp.ts
  apps/server/src/modules/BaseModule.ts
  apps/server/src/settings/SettingsController.ts
  apps/web/next.config.js
  apps/web/src/layouts/Base.tsx
  pnpm-lock.yaml
Labels: kind/feature

#706 chore(ui-ux): remove eth wallet balance poll
  apps/web/src/components/BridgeForm.tsx
Labels: kind/chore

#703 chore(core): evm to dfc - remove polling of token data
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
  apps/web/src/hooks/useWriteApproveToken.ts
Labels: kind/chore

#711 chore(ui-ux): add use address
  apps/web/src/components/WalletAddressInput.tsx
  apps/web/src/components/icons/MetaMaskIconSmall.tsx
Labels: kind/chore

#713 chore(server): skip throttle for /version
  apps/server/src/version/VersionController.ts
Labels: kind/chore

#714 fix(ui-ux): fetch balance on eth token
  apps/web/src/components/BridgeForm.tsx
Labels: kind/fix

#717 fix(core): fix claimfund race condition issue
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/fix

#721 fix(claim): fix claim error
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/fix

#720 chore(ops): update env to use usdt and usdc
  apps/server/.env
  apps/server/test-i9n/testing/SettingsController.i9n.ts
Labels: kind/chore

#722 fix(ui-ux): fixed ui alignments
  apps/web/src/components/Footer.tsx
  apps/web/src/components/commons/Socials.tsx
Labels: kind/fix

#710 chore(refactor): performance improvements
  apps/web/src/components/Footer.tsx
  apps/web/src/components/ScreenContainer.tsx
  apps/web/src/layouts/Base.tsx
  apps/web/src/pages/index.tsx
Labels: kind/chore

#718 feat(core): add app-version header to all api calls
  apps/web/src/components/Footer.tsx
  apps/web/src/hooks/useWrappedQuery.ts
  apps/web/src/layouts/Base.tsx
  apps/web/src/store/defichain.tsx
  apps/web/src/store/index.ts
  apps/web/src/store/reducers/rootReducer.ts
  apps/web/src/store/slices/versionSlice.ts
  apps/web/src/store/store.ts
Labels: kind/feature

#724 chore(ui-ux): update bridge maintenance status condition
  apps/web/src/pages/index.tsx
Labels: kind/chore

#727 feature(eth): add symbol and amount
  apps/server/Dockerfile
  apps/server/prisma/migrations/20230309051418_/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/test-i9n/ethereum/allocateDFCFund.i9n.ts
Labels: kind/feature

#729 fix(ui-ux): fixed error 404 redirects to incorrect UI
  apps/web/cypress/e2e/maintenance.spec.ts
  apps/web/src/components/ScreenContainer.tsx
Labels: kind/fix

#734 fix(e2e): always target local api for tests
  apps/web/cypress/e2e/bridge.spec.ts
  apps/web/cypress/e2e/index.spec.ts
  apps/web/cypress/e2e/maintenance.spec.ts
Labels: kind/fix

#736 chore(ui-ux): set default network to TestNet on Goerli
  apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
Labels: kind/chore

#739 chore(core): use new api endpoint
  apps/web/next.config.js
  apps/web/src/config/networkUrl.ts
Labels: kind/chore

#740 chore(web): update testnet network url
  apps/web/next.config.js
  apps/web/src/config/networkUrl.ts
Labels: kind/chore

#741 feature(core): added support for EUROC
  README.md
  apps/server/.env
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/model/VerifyDto.ts
  apps/server/src/utils/TokensUtils.ts
  apps/server/test-i9n/balances/balances.i9n.ts
  apps/server/test-i9n/defichain/balance.i9n.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  apps/server/test-i9n/testing/SettingsController.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  apps/web/public/tokens/EUROC.svg
  apps/web/public/tokens/dEUROC.svg
  apps/web/src/config/index.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/types.ts
  packages/smartcontracts/src/scripts/goerliMintApprove.ts
Labels: kind/feature

#743 chore(ops): bump jellyfish to support EUROC
  .github/workflows/ci-db-staging.yml
  .github/workflows/ci.yml
  apps/server/package.json
  apps/web/package.json
  docker-compose.yml
  package.json
  packages/smartcontracts/package.json
  pnpm-lock.yaml
Labels: kind/chore

#742 chore(ui-ux): display usdt, usdc and EUROC in web ui
  apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
Labels: kind/chore

#747 chore(e2e): enabled EUROC testcase
  apps/server/test-i9n/balances/balances.i9n.ts
  apps/server/test-i9n/defichain/balance.i9n.ts
Labels: kind/chore

#745 fix(core): only limit all amounts to 6 decimal places maximum
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/ConfirmTransferModal.tsx
  apps/web/src/components/erc-transfer/StepLastClaim.tsx
Labels: kind/fix

#749 chore(github): Remove certain codeowners
  .github/CODEOWNERS
Labels: kind/chore

#754 chore(docs): update issue templates
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-enhancement.md
  .github/ISSUE_TEMPLATE/3-general.md
  .github/ISSUE_TEMPLATE/4-ui-ux-improvements.md
  .github/ISSUE_TEMPLATE/5-translation-improvements.md
Labels: kind/chore

#753 chore(logs): add error logs
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
Labels: kind/chore

#737 feat(api): ethereum/stats API
  apps/server/src/ethereum/EthereumInterface.ts
  apps/server/src/ethereum/EthereumModule.ts
  apps/server/src/ethereum/controllers/EthereumController.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/src/utils/StatsUtils.ts
  apps/server/test-i9n/testing/ethereum/Statistics.i9n.ts
Labels: kind/feature

#755 fix(deps): update pnpm version in CI
  .github/workflows/ci-db-staging.yml
  .github/workflows/ci-e2e.yml
  .github/workflows/ci.yml
  package.json
Labels: kind/fix

#750 feat(core): bridge defichain stats
  apps/server/src/defichain/DeFiChainModule.ts
  apps/server/src/defichain/DefichainInterface.ts
  apps/server/src/defichain/controllers/StatsController.ts
  apps/server/src/defichain/services/DeFiChainStatsService.ts
  apps/server/test-i9n/defichain/stats.i9n.ts
Labels: kind/feature

#767 chore(ui-ux): updated EVM to DFC transfer success message
  apps/web/src/components/TransactionStatus.tsx
Labels: kind/chore

#756 chore(e2e): Bridge form e2e
  apps/web/cypress/e2e/bridge_form.spec.ts
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/components/InputSelector.tsx
  apps/web/src/components/commons/QuickInputCard.tsx
Labels: kind/chore

#777 chore(docs): update issue templates; uiuxImprovements
  .github/ISSUE_TEMPLATE/4-ui-ux-improvements.md
Labels: kind/chore

#793 fix(stats): fix missing WBTC stats for ethereum
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
Labels: kind/fix

#792 feat(core): support DFI as bridging token
  README.md
  apps/server/.env
  apps/server/src/AppConfig.ts
  apps/server/src/defichain/model/VerifyDto.ts
  apps/server/src/defichain/services/WhaleWalletService.ts
  apps/server/src/ethereum/EthereumInterface.ts
  apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
  apps/server/src/utils/TokensUtils.ts
  apps/server/test-i9n/defichain/verify.i9n.ts
  apps/server/test-i9n/testing/BridgeContractFixture.ts
  apps/server/test-i9n/testing/SettingsController.i9n.ts
  apps/server/test-i9n/testing/TestingModule.ts
  apps/server/test-i9n/testing/ethereum/Statistics.i9n.ts
  apps/web/public/tokens/DFI.svg
  apps/web/src/components/InputSelector.tsx
  apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
  apps/web/src/config/index.ts
  apps/web/src/layouts/contexts/NetworkContext.tsx
  apps/web/src/types.ts
  packages/smartcontracts/src/scripts/goerliMintApprove.ts
Labels: kind/feature

#763 feature(ui-ux): refetch hot wallet balance and transfer guard
  apps/web/src/components/BridgeForm.tsx
  apps/web/src/types.ts
Labels: kind/feature

#804 chore(ops): enable DFI on client
  apps/web/src/layouts/contexts/NetworkContext.tsx
Labels: kind/chore
